### ISSUE TITLE
URL Bar

### ISSUE THREAD

**Issue by Efreak** [airforsteam/Air-for-Steam#110]
> [The URL bar was removed from the main client because it doesn't provide any unique functionality. You can copy a page's URL by right-clicking on any web page within Steam and selecting "Copy Page URL."](https://github.com/Outsetini/Air-for-Steam/wiki#where-is-the-url-bar)

This is incorrect. 
- I frequently (sometimes several times a day) click a user's name in chat or in my friends list, and copy the url from the address bar in order to get their steamid64 (/profiles/...). Right clicking the page and copying the page url will give you their custom address (/id/...). There is no other way to get a user's steamid from inside the steam client without searching for it in the page source. This also applies to groups; the address bar shows the /gid/ link before it disappears and switches to the custom url for that group.
- Another (lesser) thing the url bar allows you to do is copy only part of the address, so you can paste it into the end of another url for a different website or a steam://run/appid link. Or a spreadsheet or script containing a list of appids for automation or other reasons. I have also been known to copy urls onto actual sheets of paper on occasion. Having to open another program to paste them into in order to see what they are is annoying.

Given the ability to turn the URL bar on and off from the steam menus, and the first reason above, and the relative simplicity of the theme as a whole (no images that need to be changed, so far as I can see), I would highly appreciate having the URL bar back.

**Comment by ZeroMaki** [comment]
I support this, I had to switch to metro due to the lack of this feature sadly.

**Comment by Outsetini** [comment]
Hey guys - I don't have enough time to dedicate to this right now, but I'll consider adding it as an optional tweak in the future. I'd probably keep it disabled by default to keep the simplicity intact though, and most people still won't need it.

**Comment by Outsetini** [comment]
Archiving discussion for the time being.

**Comment by Keavon** [comment]
I love what Google has done with its Material Design language, so as a long time Metro user I decided to give this a try. But without a URL bar, I have to move back to Metro because it's just a more complete and functionality-designed skin.

**Comment by Nothing4You** [comment]
Just because you don't have time to change this currently this should not be a closed issue. Closed means wontfix. If someone else has spare time they can see there's an open issue and implement this if they wanted and it'll also avoid duplicates.

**Comment by Outsetini** [comment]
A fair point, indeed.

**Comment by maNggo666** [comment]
Are there any news about this? =)
