### ISSUE TITLE
Change account interface

### ISSUE THREAD

**Issue by peoky** [airforsteam/Air-for-Steam#201]
Thanks for your great skin, but "change account interface" has a minor problem, please fix it.

![11](https://user-images.githubusercontent.com/40545693/44955323-adf3e500-aec6-11e8-8ce4-7901fbeafb74.jpg)

**Comment by Outsetini** [comment]
I'm not seeing an issue on Windows. What specifically are you seeing wrong? What OS are you using?

**Comment by peoky** [comment]
Username and Password "Text Boxes" have no "Margins" or "Labels".

**Comment by peoky** [comment]
Hi
Sorry, this problem was because of my screen resolution, this issue can be closed now.
