### ISSUE TITLE
No way to tell if a game runs through Steam Play / Proton

### ISSUE THREAD

**Issue by Vash63** [airforsteam/Air-for-Steam#205]
As far as I can tell, there's no icon or label showing if a game uses Steam Play or not when this theme is enabled.

As an example, with the default theme the circled notice is visible:
![screenshot from 2018-09-16 19-34-02](https://user-images.githubusercontent.com/3086017/45599215-c34d3100-b9e7-11e8-8457-1c553c3df38b.png)

**Comment by airforsteam** [comment]
Duplicate #200 - this should be fixed now, please check the latest commit and verify. :)
