### ISSUE TITLE
Menu stays focused when pressing "View friends list"

### ISSUE THREAD

**Issue by AccountOneOff** [airforsteam/Air-for-Steam#206]
When the menu item "View friends list" is pressed the hamburger menu doesn't close unless the hamburger menu button is double-clicked.

Here's the menu on-top of Firefox:

![screenshot from 2018-09-17 19-01-43](https://user-images.githubusercontent.com/15083452/45660551-2903f080-baae-11e8-849f-42185bbfb4e4.png)

**Comment by airforsteam** [comment]
Hmm, I'm not able to reproduce this issue on Windows, and it's not something that falls into the category of things that skins can usually fix. The only solution that I can think of that would really do anything is to remove the menu item altogether, which isn't a great answer...

Can you check to see if the same issue occurs with the friends menu on vanilla Steam?

I just pushed a commit that has a .01% chance to fix it, just a shot in the dark but I suspect the Steam code has something in it that says to specifically close the "Friends" menu after clicking on that link.

**Comment by AccountOneOff** [comment]
Ok yeah it looks like a Linux client problem. Sorry about that.
