### ISSUE TITLE
Missing Family View (Parental Control) switch button

### ISSUE THREAD

**Issue by MarcinOrlowski** [airforsteam/Air-for-Steam#210]
I am using recent Air-for-Steam-2018-0928 and it lacks Family View toggle button that is usually visible on title bar. This makes it impossible to switch between parental controlled mode and full mode

**Comment by airforsteam** [comment]
Check out the FAQ for the Family View button: https://github.com/airforsteam/Air-for-Steam/wiki/questions#how-do-i-use-family-view-with-air
