### ISSUE TITLE
Malformed "Steam Input Per-Game Setting" Dropdown in Game Properties

### ISSUE THREAD

**Issue by kakolisgay** [airforsteam/Air-for-Steam#212]
In the latest release of Air for Steam there's a malformed dropdown box in the Game Properties Window. As far as I am aware this is not an OS-dependant setting
*For note I am opted into the Steam Beta Client*

### Screenshots
[Air for Steam: Window](https://i.imgur.com/PkSZpZk.png)
[Air for Steam: Window Dropdown Toggled](https://i.imgur.com/5x8zPVu.png)
[Stock: Window](https://i.imgur.com/vqjciIu.png)
[Stock: Window Dropdown Toggled](https://i.imgur.com/LvycxqN.png)
[Inspector: Dropdown](https://i.imgur.com/lcDD95I.png) (SteamInputPerGameCombo / ComboBox)

[Steam Discussions Post](https://steamcommunity.com/groups/airforsteam/discussions/1/1736595227862341128/)

**Comment by lKobi** [comment]
This is related to a new Steam Client Update, the Skin just needs to be updated.

**Comment by airforsteam** [comment]
Thank you very much for this detailed bug report, exactly what I needed!
