### ISSUE TITLE
I can't change theme even though I copy the necessary files from "+Extras"

### ISSUE THREAD

**Issue by Dumbledorf** [airforsteam/Air-for-Steam#215]
I want to use the dark theme, which looks like the image below, but it won't enable even though I copy the files I need to copy from the folder "+Extras".

![Dark theme](https://i.imgur.com/MPwIuqq.png)

It keeps looking like this.

![Dark theme](https://i.imgur.com/2qTKryf.png)

**Comment by Ash258** [comment]
That upper theme is "Spotify Theme"

You need to: 

1. Copy everything from `Extras\Themes\Dark` to root folder of Skin
1. Open File `config.ini`
1. Uncomment line, which contains spotify skin. (and comment default sking line)

https://github.com/airforsteam/Air-for-Steam/blob/master/config.ini#L48

**Comment by Dumbledorf** [comment]
That worked. Thank you!
