### ISSUE TITLE
Jan 17th Beta Update broke some things

### ISSUE THREAD

**Issue by kakolisgay** [airforsteam/Air-for-Steam#216]
[Value has pushed a small-ish change](https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108827819236) to the beta branch that adds a new checkbox and dropdown to Game Properties and modifies the text held in the "Runs via Steam Play" Textbox.
*For note I am opted into the Steam Beta Client*

### Screenshots
[Air for Steam: "Runs via Steam Play"](https://i.imgur.com/ZkEOeRO.png)
[Stock: "Runs via Steam Play"](https://i.imgur.com/39PVgiP.png) (compatdescription / RichText)

[Air for Steam: "Steam Play Dropdown"](https://i.imgur.com/ABx4Ii1.png)
[Air for Steam: "Steam Play Dropdown" Checked](https://i.imgur.com/8jNAjq0.png)
[Air for Steam: "Steam Play Dropdown" Dropped down](https://i.imgur.com/EcUkc4M.png)
[Stock: "Steam Play Dropdown"](https://i.imgur.com/6ZDk914.png) (SteamPlayOverrideCheck / CheckButton)
[Stock: "Steam Play Dropdown" Checked](https://i.imgur.com/NMyt6Ox.png) (SteamPlayOverrideCombo / ComboBox)
[Stock: "Steam Play Dropdown" Dropped down](https://i.imgur.com/3QUNkZq.png)

[Steam Discussions Post](https://steamcommunity.com/groups/airforsteam/discussions/1/1744483505469597452/)

**Comment by airforsteam** [comment]
Can you let me know if this change fixes the issue?

**Comment by kakolisgay** [comment]
A new checkbox has also been added to game shortcuts. I check tomorrow and see if the other stuff if fixed though

**Comment by airforsteam** [comment]
Game shortcuts?

**Comment by kakolisgay** [comment]
@airforsteam Custom games added to steam have a new button for steam play.

**Comment by kakolisgay** [comment]
@airforsteam Just looked through the latest commit and everything looks fine now, although custom game shortcuts have a hr line going through the buttons.

**Comment by airforsteam** [comment]
Okay, that should fix the divider issue. Thanks for the screenshot. :)
