### ISSUE TITLE
"Log out of account: " without user name.

### ISSUE THREAD

**Issue by AlexVincent525** [airforsteam/Air-for-Steam#218]
The ":" defined by steam's localization. (Screenshot 1)
![image](https://user-images.githubusercontent.com/15884415/52256425-9b884680-2951-11e9-8c08-d6a7abcfd718.png)

Air For Steam makes account's name (account_name_label) disappear, but from my point of view, it can be placed and limit it's width, Like this one. It seems to be better to match with the ":" (Screenshot 2)
![image](https://user-images.githubusercontent.com/15884415/52256552-12254400-2952-11e9-8ade-f4864258efe3.png)

Or it can be removed from account menu. (Screenshot 3)
![image](https://user-images.githubusercontent.com/15884415/52257450-d7bda600-2955-11e9-994f-6bca30abdc02.png)

PR can be made if this is granted or agreed by most of people. :)

**Comment by airforsteam** [comment]
I agree - I was having a hard time figuring out what to do with this. It's not well coded on Valve's end. The height and width of the menu are set manually and I don't have a way to change them. I adjusted the spacing of the items a bit and removed the last entry and it seems to look fine that way.

**Comment by AlexVincent525** [comment]
Yes those spacing fits better than before, but still, the balance might take a chance to be displayed. :)
