### ISSUE TITLE
"View my Wallet"without account balance.

### ISSUE THREAD

**Issue by AlexVincent525** [airforsteam/Air-for-Steam#219]
As a new account menu came out, the balance of the account was gone. (Zero height and width by air) (Screenshot 1)
![image](https://user-images.githubusercontent.com/15884415/52257924-f6bd3780-2957-11e9-8e43-4a2ac7d02edd.png)

We can bring it back like this. (Screenshot 2).
![image](https://user-images.githubusercontent.com/15884415/52257982-36841f00-2958-11e9-980a-80ada49ad25e.png)

PR can be made if this is granted or agreed by most of people. :)

**Comment by airforsteam** [comment]
See #218 for my fix.
