### ISSUE TITLE
Announcement Toggle

### ISSUE THREAD

**Issue by AlexVincent525** [airforsteam/Air-for-Steam#220]
Announcement button was removed by air. (Screenshot 1)
![image](https://user-images.githubusercontent.com/15884415/52288539-60b0fd80-29a7-11e9-9ca6-b97eb2fa4494.png)

I personally bring it back with an icon. It will only appear when there's announcements. (Screenshot 2)
![image](https://user-images.githubusercontent.com/15884415/52288312-ed0ef080-29a6-11e9-9374-25e7d3ab97d4.png)

PR can be made if this is granted or agreed by most of people. :)

**Comment by airforsteam** [comment]
This is a feature I don't plan to bring to Air since it isn't necessary for most users.

**Comment by AlexVincent525** [comment]
Comsidered it's a cut off and add into wiki? I'll keep this one my own.
