### ISSUE TITLE
Steam Beta Library support

### ISSUE THREAD

**Issue by Nik-mmzd** [airforsteam/Air-for-Steam#230]
Well... New Library is fully unusable with Air for Steam
![image](https://user-images.githubusercontent.com/19509291/65077153-106d3580-d9a3-11e9-9ced-42a3337d9870.png)

**Comment by airforsteam** [comment]
https://github.com/airforsteam/Air-for-Steam/commit/2738faa099d4c0a2cfa4fa393156cfdbb35ca2ff should fix the issue 👍
